### ISSUE TITLE
Unable to query data from a valid json inserted using Documents API with stargate 1.0.5 and DSE 6.8.9

### ISSUE THREAD

**Issue by msmygit** [stargate/stargate#632] opened 2021-02-01 22:41 UTC
Unable to query the inserted record from a valid JSON file using the docsapi.

##### Versions used:
1. Stargate `1.0.5` docker image
2. DSE `6.8.9` docker image

Sample valid json attached for reference. I had to rename `.json` to `.txt` as GH wouldn't allow it as-is.
[fixed_copy.txt](https://github.com/stargate/stargate/files/5907247/fixed_copy.txt)

##### Error or no data fetched scenario

For a query `http://localhost:8082/v2/namespaces/devices/collections/inventory?where={"department" : {"$eq" : "HR"}}`, I get no records. Another query which doesn't pull records back is: `http://localhost:8082/v2/namespaces/devices/collections/inventory?where={"location.locationInstructions": {"$in":["front%20door"]}}`. I always end up with the following:

```
{
    "data": {}
}
```

If I query the CQL table directly, I can see the record:
```
cqlsh> SELECT * FROM devices.inventory WHERE text_value='HR';

 key                                  | p0       | p1       | p2         | p3 | p4 | p5 | p6 | p7 | p8 | p9 | p10 | p11 | p12 | p13 | p14 | p15 | p16 | p17 | p18 | p19 | p20 | p21 | p22 | p23 | p24 | p25 | p26 | p27 | p28 | p29 | p30 | p31 | p32 | p33 | p34 | p35 | p36 | p37 | p38 | p39 | p40 | p41 | p42 | p43 | p44 | p45 | p46 | p47 | p48 | p49 | p50 | p51 | p52 | p53 | p54 | p55 | p56 | p57 | p58 | p59 | p60 | p61 | p62 | p63 | bool_value | dbl_value | leaf       | text_value
--------------------------------------+----------+----------+------------+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------------+-----------+------------+------------
 3473ae5d-682f-42a3-9614-8efa3412e0d0 | [000000] | location | department |    |    |    |    |    |    |    |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |       null |      null | department |         HR

(1 rows)
cqlsh>
```

**Comment by EricBorczuk** [comment] 2021-02-01 22:48
This is a dupe of https://github.com/stargate/stargate/issues/571, so will close for now; will prioritize that issue

**Closed by EricBorczuk** 2021-02-01 22:48 UTC
