### ISSUE TITLE
Prevent Schema update failure on Stargate due to `CompositeType` / `DynamicCompositeType` inclusion in table definition

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/stargate#2144] opened 2022-10-07 15:02 UTC
CompositeType are not supported in stargate schema.

Create table as below:

```
CREATE TABLE IF NOT EXISTS jtest.composite(
     "name" text,
     "compTest" 'org.apache.cassandra.db.marshal.DynamicCompositeType(B=>org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.BytesType),D=>org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.DoubleTyp)',
     "shard" int,
     PRIMARY KEY(name))
```

Error happened while updating the schema

```
java.lang.IllegalArgumentException: Unknown type mapping for class org.apache.cassandra.db.marshal.DynamicCompositeType
        at com.datastax.oss.driver.shaded.guava.common.base.Preconditions.checkArgument(Preconditions.java:216)
        at io.stargate.db.dse.impl.Conversion.getTypeFromInternal(Conversion.java:667)
        at io.stargate.db.dse.impl.SchemaConverter.columnType(SchemaConverter.java:87)
        at io.stargate.db.dse.impl.SchemaConverter.columnType(SchemaConverter.java:26)
        at io.stargate.db.datastore.common.AbstractCassandraSchemaConverter.convertColumn(AbstractCassandraSchemaConverter.java:176)
        at io.stargate.db.datastore.common.AbstractCassandraSchemaConverter.lambda$convertColumns$1(AbstractCassandraSchemaConverter.java:168)
```

**Comment by tatu-at-datastax** [comment] 2022-10-07 15:03
And this is via CQL?

**Comment by maheshrajamani** [comment] 2022-10-07 15:07
Yes. Table can be created via stargate cql. Error happens when schema is updated. Conversion code is missing CompositeType implementation. https://github.com/stargate/stargate/blob/master/persistence-dse-6.8/src/main/java/io/stargate/db/dse/impl/Conversion.java#:~:text=Preconditions.checkArgument(

**Comment by tatu-at-datastax** [comment] 2022-10-07 15:50
So I guess the first thing then is to write a test for this type: hopefully we have existing ones to modify. But then adding actual handling. Is [Dynamic]CompositeType something that all backends support?

**Comment by JeremiahDJordan** [comment] 2023-01-13 21:37
Yes.  All versions of Cassandra and DSE support it.

**Comment by tatu-at-datastax** [comment] 2023-01-14 01:10
Another example by @JeremiahDJordan, from Python tests:

```
CREATE TABLE keyspace.table (
       k int PRIMARY KEY,
       c1 'DynamicCompositeType(s => UTF8Type, i => Int32Type)',
       c2 Text)
```

**Comment by ivansenic** [comment] 2023-01-16 09:41
Should this be prioritized?

**Comment by tatu-at-datastax** [comment] 2023-01-23 21:22
I am working on this: issue is reproducible as described.

Resolving schema updater problem appears easy enough, but now trying to see if resulting table could be accessed if DCT-valued column is not actively use. Currently:

1. INSERT succeeds
2. SELECT withOUT DCT-column succeeds
3. SELECT WITH DCT-column fails with a low-level Driver decoding problem

Issue is probably due to use of "Custom" type id for DCT but not quite sure yet if and how this should be resolved.

**Comment by tatu-at-datastax** [comment] 2023-01-28 00:11
Merge to `v1` for Stargate v1.0.73; will do a PR for merging into Stargate v2 as well (`main` branch).

**Closed** 2023-01-31 00:18 UTC
