### ISSUE TITLE
Pre-populate playground tabs with non-system keyspaces info

### ISSUE THREAD

**Issue by jorgebay** [stargate/stargate#371] opened 2020-11-03 15:39 UTC
As a followup of #238, we should add basic pre-populated queries in the playground tabs body to facilitate users getting started with GraphQL API.

For example: 

<img width="678" alt="Screenshot 2020-11-03 at 16 37 43" src="https://user-images.githubusercontent.com/2931196/98006796-f551c500-1df2-11eb-8354-1aca3792b83f.png">

**Comment by dougwettlaufer** [comment] 2020-11-03 15:49
I thought about doing this but the problem is we won't know the schema in order to create a query. Although in the `graphql-schema` tab I did add one for pulling keyspaces since we know what that is ahead of time.

**Comment by jorgebay** [comment] 2020-11-10 11:48
I think that if we share some internal state of the schemas, it's possible to generate them on the fly.

**Comment by jeffreyscarpenter** [comment] 2023-05-24 21:27
won't fix

**Closed by jeffreyscarpenter** 2023-05-24 21:27 UTC
Labels: enhancement, GraphQL CQL-first
