### ISSUE TITLE
Operation failed - received 0 responses and 1 failures: READ_TOO_MANY_TOMBSTONES when using where=

### ISSUE THREAD

**Issue by mvandenbrink** [stargate/stargate#711] opened 2021-02-23 18:25 UTC
The last couple of weeks I'm doing some small performance test on Stargate for the Document API. I've a small docker setup with 3 cassandra nodes and 1 Stargate node. I bulk load 850.000 documents with the PUT method and trying to get data with the WHERE filter to test the performance. In version 1.0.9 I'm getting the READ_TOO_MANY_TOMBSTONES error on some WHERE filter requests, not on all. For instance when I use in Postman the WHERE filter on zipcode:

```
{{baseUrl}}/v2/namespaces/test/collections/dossiers?page-size=10&where={ "zipcode": { "$eq": "6521MH" } }
```

... the request takes 1 minute and 23.23 seconds. A request using the WHERE filter on house number:

```
{{baseUrl}}/v2/namespaces/test/collections/dossiers?page-size=10&where={"houseNumber": {"$eq": "21" } }
```

... takes 189ms. And using the WHERE filter on place:

```
{{baseUrl}}/v2/namespaces/test/collections/dossiers?page-size=10&where={"place": {"$eq": "Putten" } }
```

... the request failed with an HTTP 500 Internal Server error.  The response in Postman was "org.apache.cassandra.stargate.exceptions.ReadFailureException: Operation failed - received 0 responses and 1 failures: READ_TOO_MANY_TOMBSTONES from 172.21.0.2: 7000". 

```
ERROR [2021-02-23 18:20:17,184] io.stargate.web.docsapi.resources.DocumentResourceV2: Error when executing request
! org.apache.cassandra.stargate.exceptions.ReadFailureException: Operation failed - received 0 responses and 1 failures: READ_TOO_MANY_TOMBSTONES from 172.21.0.2:7000
! at io.stargate.db.cassandra.impl.Conversion.toExternal(Conversion.java:315)
! at io.stargate.db.cassandra.impl.Conversion.convertInternalException(Conversion.java:472)
! at io.stargate.db.cassandra.impl.CassandraPersistence$CassandraConnection.lambda$executeRequestOnExecutor$0(CassandraPersistence.java:443)
! at io.stargate.db.cassandra.impl.CassandraPersistence.lambda$runOnExecutor$1(CassandraPersistence.java:268)
! ... 5 common frames omitted
! Suppressed: org.apache.cassandra.exceptions.ReadFailureException: Operation failed - received 0 responses and 1 failures
!       at org.apache.cassandra.service.ReadCallback.awaitResults(ReadCallback.java:137)
!       at org.apache.cassandra.service.ReadCallback.get(ReadCallback.java:143)
!       at org.apache.cassandra.service.StorageProxy$SingleRangeResponse.waitForResponse(StorageProxy.java:2071)
!       at org.apache.cassandra.service.StorageProxy$SingleRangeResponse.computeNext(StorageProxy.java:2081)
!       at org.apache.cassandra.service.StorageProxy$SingleRangeResponse.computeNext(StorageProxy.java:2054)
!       at org.apache.cassandra.utils.AbstractIterator.hasNext(AbstractIterator.java:47)
!       at org.apache.cassandra.db.transform.BaseIterator.tryGetMoreContents(BaseIterator.java:144)
!       at org.apache.cassandra.db.transform.BaseIterator.hasMoreContents(BaseIterator.java:111)
!       at org.apache.cassandra.db.transform.BasePartitions.hasNext(BasePartitions.java:105)
!       at org.apache.cassandra.service.StorageProxy$RangeCommandIterator.computeNext(StorageProxy.java:2129)
!       at org.apache.cassandra.service.StorageProxy$RangeCommandIterator.computeNext(StorageProxy.java:2092)
!       at org.apache.cassandra.utils.AbstractIterator.hasNext(AbstractIterator.java:47)
!       at org.apache.cassandra.db.transform.BasePartitions.hasNext(BasePartitions.java:92)
!       at org.apache.cassandra.cql3.statements.SelectStatement.process(SelectStatement.java:786)
!       at org.apache.cassandra.cql3.statements.SelectStatement.processResults(SelectStatement.java:438)
!       at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:416)
!       at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:289)
!       at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:117)
!       at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:225)
!       at org.apache.cassandra.cql3.QueryProcessor.processPrepared(QueryProcessor.java:532)
!       at org.apache.cassandra.cql3.QueryProcessor.processPrepared(QueryProcessor.java:509)
!       at io.stargate.db.cassandra.impl.StargateQueryHandler.processPrepared(StargateQueryHandler.java:199)
!       at org.apache.cassandra.transport.messages.ExecuteMessage.execute(ExecuteMessage.java:146)
!       at io.stargate.db.cassandra.impl.CassandraPersistence$CassandraConnection.lambda$executeRequestOnExecutor$0(CassandraPersistence.java:436)
!       ... 6 common frames omitted
! Causing: java.util.concurrent.CompletionException: org.apache.cassandra.stargate.exceptions.ReadFailureException: Operation failed - received 0 responses and 1 failures: READ_TOO_MANY_TOMBSTONES from 172.21.0.2:7000
! at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
! at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
! at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
! at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
! at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
! at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
! at io.stargate.db.cassandra.impl.CassandraPersistence.lambda$runOnExecutor$1(CassandraPersistence.java:277)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:165)
! at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:137)
! at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113)
! at java.lang.Thread.run(Thread.java:748)
172.21.0.1 - - [23/Feb/2021:18:20:17 +0000] "GET /v2/namespaces/test/collections/dossiers?page-size=10&where={%22place%22:%20{%22$eq%22:%20%22Putten%22%20}%20} HTTP/1.1" 500 164 "-" "PostmanRuntime/7.26.10" 865
```

There are 2 problems. The first one is the error, the second is the unpredictable response time when using the WHERE filter. With a small data set  there is no problem with either of them.

**Comment by EricBorczuk** [comment] 2021-02-23 20:24
Hello there - one of the problems I have a quick solution for; the long search response time is a known issue and will be fixed by https://github.com/stargate/stargate/pull/681 (which should be released as part of 1.0.10). You should expect that the search will take tens of milliseconds instead of seconds or even a minute - that's my bad...

As far as tombstones go, I'm curious as to how you loaded documents into the system, since searching would not create tombstones.  However, if you find that you are replacing existing documents with new ones very frequently, you would be creating an excessive number of tombstones. Inserting brand new documents would not cause any tombstones to be created.

So I guess the question is - as you are testing this, are you using a fresh database cluster each time? are you reusing document ID's? (this would cause tombstones)

**Comment by EricBorczuk** [comment] 2021-02-23 21:14
Just to let you know, I edited the above, it will be released in the upcoming release `1.0.11`. Sorry for any confusion!

**Comment by mvandenbrink** [comment] 2021-02-24 06:36
Hi Eric,

I had the same reaction (with my little knowledge of Cassandra), why do I get a "read too many tombstones" error after an initial load where I only did inserting documents via the Document PUT API and nothing else. My load script is a very small and easy Javascript with 2 HTTP requests. The first HTTP request for the authentication process to receive the authToken. This authToken is used in the second HTTP request, see the snippet below:
	
```
		const req = http.request({
				hostname: 'localhost',
				path: '/v2/namespaces/test/collections/dossiers/' + dossier.dossierNumber,
				port: 8082,
				method: 'PUT',
				headers: {
					'X-Cassandra-Token': authToken,
					'Content-Type': 'application/json; charset=utf-8;',
					'Content-Length': dossierData.length
				},
				rejectUnauthorized: false,
			}, function(res) {
				// do some stuff on the res(ult)
			});
		});
```

When I run my test I remove all the containers, create 3 Cassandra containers and 1 Stargate container in there own docker network which is also created. The namespace and collection were made with Postman after the initial docker setup. The initial load is run from the command prompt in 9 parallel processes to load 850.000 documents (8 times 100.000 and the last one with over 50.000 documents). This is taking around 35 minutes to complete. After the initial load I use Postman to get 1 document, then a list with documents with a page size of 10 and that the WHERE filter.

So as you can see, nothing special, no delete and not reusing the document ID's. The dossierNumber is an unique index key in the database were the export is from.

**Comment by EricBorczuk** [comment] 2021-02-24 20:44
Hmm if you are certain that the value of `dossier.dossierNumber` is changing from request to request and is not reused, then I am stumped.

If you are using 9 parallel processes, is it possible that you are getting dossier number collisions that way?

Also, any full code snippets or sample data that you are permitted to send through would be helpful in reproducing the issue on my own machine :)

**Comment by mvandenbrink** [comment] 2021-02-24 21:40
Eric, I can send you the script, the data would be an issue. Need to prepare it somewhat because it is real data. Is it okay if I ask Michel for your email address to send the script, instructions and a data set?

**Comment by EricBorczuk** [comment] 2021-02-24 22:14
Absolutely, looking forward to helping out in any way I can!

**Comment by mvandenbrink** [comment] 2021-02-26 14:17
Hello Eric, I can't reproduce the error in version 1.0.11. Seems to be fixed in there and the performance made a great improvement, thanks for the great work.

**Closed** 2021-04-26 22:20 UTC
