### ISSUE TITLE
swagger.json bug from `openapi-generator`

### ISSUE THREAD

**Issue by caniko** [stargate/stargate#2445] opened 2023-02-15 10:52 UTC
I wanted to generate `dart-dio` package for Stargate (flutter integration), but got an error during generation. Seems to be an error in the primary key declaration in `swagger.json`.

**Considerations**
1. I have my MVP working already, this was for further development.
2. Have you considered upgrading to OpenAPI 3.0? Swagger 2.0 is outdated. Not sure how complex this switch would be.

Command:
```shell
openapi-generator generate --input-spec stargate_swagger.json --output stargate_dart-dio --generator-name dart-dio --additional-properties=pubName=stargate_api_client,pubVersion=2.0,pubAuthorEmail=canhtart@gmail.com --global-property skipFormModel=false
```

Error message:
```error
openapi-generator generate --input-spec stargate_swagger.json --output stargate_dart-dio --generator-name dart-dio --additional-properties=pubName=stargate_api_client,pubVersion=2.0,pubAuthorEmail=canhtart@gmail.com --global-property skipFormModel=false
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 0
Errors: 
        -attribute info is missing
        -attribute paths.'/v1/keyspaces/{keyspaceName}/tables/{tableName}/rows/{primaryKey}'. Declared path parameter primaryKey needs to be defined as a path parameter in path or operation level

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:620)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:647)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:465)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
make: *** [makefile:2: star-dio] Error 1
```

**Comment by ivansenic** [comment] 2023-02-15 13:44
Where did you the `swagger.json`?

**Comment by caniko** [comment] 2023-02-15 14:01
This is accessible through http://127.0.0.1:8082/swagger.json on K8ssandra after port forwarding from the stargate service is active.

**Comment by caniko** [comment] 2023-02-15 14:02
Mine should be the same as any others :rocket: (... I wish)

[stargate_swagger.zip](https://github.com/stargate/stargate/files/10743716/stargate_swagger.zip)

**Comment by ivansenic** [comment] 2023-02-15 14:03
Possible duplicate of https://github.com/stargate/stargate/issues/1011.

Unfortunately, Swagger in stargate v1 is completly broken. We fixed a lot of things in stargate v2. Would you consider upgrading?

**Comment by ivansenic** [comment] 2023-02-15 14:04
@jeffreyscarpenter Is there any external `swagger.json` available for download?

**Comment by jeffreyscarpenter** [comment] 2023-02-15 18:25
@ivansenic do you mean available on the docs site? I don't believe so.

**Comment by ivansenic** [comment] 2023-02-16 10:57
> @ivansenic do you mean available on the docs site? I don't believe so.

Yes that's what I mean.

**Comment by jeffreyscarpenter** [comment] 2023-02-16 15:46
No, we have not made this available on the docs site. Is there a way we could do this and make sure it is kept up to date when we do releases? @johnsmartco

**Comment by caniko** [comment] 2023-02-17 14:21
> We fixed a lot of things in stargate v2. Would you consider upgrading?

I would love to @ivansenic, but I am on K8ssandra and there is no support for V2 yet.

**Comment by jeffreyscarpenter** [comment] 2023-02-19 00:41
> No, we have not made this available on the docs site. 

Actually I was incorrect, the v2 Swagger references are available

https://stargate.io/docs/latest/develop/attachments/restv2.html
https://stargate.io/docs/latest/develop/attachments/docv2.html

**Closed** 2024-11-02 23:18 UTC
Labels: bug, stargate-v1
