### ISSUE TITLE
Array-based filter path.[*] returns empty data

### ISSUE THREAD

**Issue by ErickRamirezDS** [stargate/stargate#1247] opened 2021-09-14 00:27 UTC
This issue was reported by [Debdeep Das](https://stackoverflow.com/users/11863447/debdeep-das) on https://stackoverflow.com/questions/69167045/.

For document:

```
{
    "id": "1234",
    "vowels": "aeu",
    "alpha":[
        "xyz",
        "efgh"
    ],
    "new": [
        {"name":"nam1"},
        {"name":"nam2"}
    ]
}
```

The filter `where={"alpha.[*]":{"$eq":"xyz"}}` returns no data.

**Comment by ivansenic** [comment] 2021-09-14 07:24
I can confirm this is a bug currently, the wildcards `*` and `[*]` work as expected if they are not at the end of the search path. For example, `x.[*].z`.. I will create a fix asap and it will be included in the next release..

**Comment by ivansenic** [comment] 2021-09-14 10:13
There could be some serious indexing implications that might not make this actually possible. We count to have a leaf name (or array index) that's being searched for in order to utilize the indexes. If this is missing, we don't have any path related index to use and this can result in failing back to the value index. However, since value index matches different paths, it would not be as effective.

I will check with my team and come back with more information.

**Comment by mindflayer** [comment] 2021-11-11 20:30
Hi there, any news about this issue?
Thanks!

**Comment by mindflayer** [comment] 2021-11-12 13:31
> If you say that this is a feature that is very important to you and stops you from progressing further

Many thanks for asking, I really appreciate it.
The first use case we encountered has been redesigned using a map instead of an array of values, after reading this issue.
With the same approach, of course, we could solve different problems.
I would still consider investing time in it if you think it could be solved in some way. What is nice in a Document DB is the fact that you don't need big transformations from the way you store data to the one consumed by your clients.
I am not a Cassandra expert, but may have a look at the way Elasticsearch deals with the same problem.

**Comment by ivansenic** [comment] 2021-11-12 13:57
@mindflayer The Elasticsearch is not storing the data as we are. We are having a Cassandra as a data store, thus storing JSON is way more challenging. This implies that queries the data and supporting all the standard filters and aggregations is sometimes not as easy, or simply comes with an extra cost.

**Comment by mindflayer** [comment] 2021-11-12 14:17
Cannot you transform it in a list of arrays?
```json
{
    "tags": ["foo", "bar"]
}
```
Could be internally stored as:
```json
[
{"tags": "foo"},
{"tags": "bar"}
]
```
I guess this way the query would be: `where={"[*].tags":{"$eq":"foo"}}` instead of `where={"tags.[*]":{"$eq":"foo"}}`.

**Comment by ivansenic** [comment] 2021-11-16 14:22
@mindflayer Not really.. Have a look here -> https://www.datastax.com/blog/2021/04/stargate-documents-api-storage-mechanisms-search-filters-and-performance-improvements on how the data is stored in the C table.

**Comment by GeorgeCrossIV** [comment] 2022-09-07 03:02
Checking to see if there is any movement on this issue. I cannot map or transform the JSON data that I'm storing. However, I need the ability to search the leaf nodes of the array.

**Closed** 2023-10-11 18:33 UTC
Labels: enhancement, documents API
