### ISSUE TITLE
Restarting coordinator changes hash of the `DescribeKeyspace` response

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1997] opened 2022-07-25 14:43 UTC
I noticed a strange behavior in the Stargate V2, where bridge is responding with inconsistent keyspace `hash`, if the coordinator is restarted.

For the same keyspace, that has not been altered, I first get hash `1531909307` and then after restarting I get another hash `2009911283`.

First request:
```
{"level":"debug","time":"2022-07-25T16:33:54.200526011+02:00","message":"Received response","workerID":"g0c0","call type":"unary","call":"stargate.StargateBridge.DescribeKeyspace","input":"keyspace_name:\"docs_crud_basic\" hash:<value:419817556 >","metadata":{"x-cassandra-token":["904b7638-2750-4192-b661-a1728d9456b4"]},"response":"cql_keyspace:<name:\"docs_crud_basic\" options:<key:\"durable_writes\" value:\"true\"> options:<key:\"replication\" value:\"{ 'class': 'SimpleStrategy', 'replication_factor': 1 }\"> global_name:\"docs_crud_basic\"> tables:<name:\"docs_collection\" options:<key:\"comment\" value:\"\"> options:<key:\"ttl\" value:\"0\"> partition_key_columns:<type:<basic:VARCHAR> name:\"key\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p0\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p1\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p2\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p3\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p4\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p5\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p6\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p7\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p8\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p9\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p10\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p11\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p12\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p13\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p14\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p15\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p16\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p17\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p18\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p19\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p20\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p21\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p22\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p23\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p24\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p25\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p26\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p27\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p28\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p29\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p30\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p31\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p32\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p33\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p34\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p35\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p36\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p37\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p38\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p39\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p40\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p41\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p42\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p43\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p44\"> columns:<type:<basic:BOOLEAN> name:\"bool_value\"> columns:<type:<basic:DOUBLE> name:\"dbl_value\"> columns:<type:<basic:VARCHAR> name:\"leaf\"> columns:<type:<basic:VARCHAR> name:\"text_value\"> clustering_orders:<key:\"p0\" value:ASC> clustering_orders:<key:\"p1\" value:ASC> clustering_orders:<key:\"p10\" value:ASC> clustering_orders:<key:\"p11\" value:ASC> clustering_orders:<key:\"p12\" value:ASC> clustering_orders:<key:\"p13\" value:ASC> clustering_orders:<key:\"p14\" value:ASC> clustering_orders:<key:\"p15\" value:ASC> clustering_orders:<key:\"p16\" value:ASC> clustering_orders:<key:\"p17\" value:ASC> clustering_orders:<key:\"p18\" value:ASC> clustering_orders:<key:\"p19\" value:ASC> clustering_orders:<key:\"p2\" value:ASC> clustering_orders:<key:\"p20\" value:ASC> clustering_orders:<key:\"p21\" value:ASC> clustering_orders:<key:\"p22\" value:ASC> clustering_orders:<key:\"p23\" value:ASC> clustering_orders:<key:\"p24\" value:ASC> clustering_orders:<key:\"p25\" value:ASC> clustering_orders:<key:\"p26\" value:ASC> clustering_orders:<key:\"p27\" value:ASC> clustering_orders:<key:\"p28\" value:ASC> clustering_orders:<key:\"p29\" value:ASC> clustering_orders:<key:\"p3\" value:ASC> clustering_orders:<key:\"p30\" value:ASC> clustering_orders:<key:\"p31\" value:ASC> clustering_orders:<key:\"p32\" value:ASC> clustering_orders:<key:\"p33\" value:ASC> clustering_orders:<key:\"p34\" value:ASC> clustering_orders:<key:\"p35\" value:ASC> clustering_orders:<key:\"p36\" value:ASC> clustering_orders:<key:\"p37\" value:ASC> clustering_orders:<key:\"p38\" value:ASC> clustering_orders:<key:\"p39\" value:ASC> clustering_orders:<key:\"p4\" value:ASC> clustering_orders:<key:\"p40\" value:ASC> clustering_orders:<key:\"p41\" value:ASC> clustering_orders:<key:\"p42\" value:ASC> clustering_orders:<key:\"p43\" value:ASC> clustering_orders:<key:\"p44\" value:ASC> clustering_orders:<key:\"p5\" value:ASC> clustering_orders:<key:\"p6\" value:ASC> clustering_orders:<key:\"p7\" value:ASC> clustering_orders:<key:\"p8\" value:ASC> clustering_orders:<key:\"p9\" value:ASC> indexes:<name:\"docs_collection_dbl_value_idx\" column_name:\"dbl_value\"> indexes:<name:\"docs_collection_bool_value_idx\" column_name:\"bool_value\"> indexes:<name:\"docs_collection_text_value_idx\" column_name:\"text_value\"> indexes:<name:\"docs_collection_leaf_idx\" column_name:\"leaf\">> hash:<value:1531909307 >","error":null}
```

Restart coordinator, second request:
```
{"level":"debug","time":"2022-07-25T16:38:39.745559752+02:00","message":"Received response","workerID":"g0c0","call type":"unary","call":"stargate.StargateBridge.DescribeKeyspace","input":"keyspace_name:\"docs_crud_basic\" hash:<value:419817556 >","metadata":{"x-cassandra-token":["904b7638-2750-4192-b661-a1728d9456b4"]},"response":"cql_keyspace:<name:\"docs_crud_basic\" options:<key:\"durable_writes\" value:\"true\"> options:<key:\"replication\" value:\"{ 'class': 'SimpleStrategy', 'replication_factor': 1 }\"> global_name:\"docs_crud_basic\"> tables:<name:\"docs_collection\" options:<key:\"comment\" value:\"\"> options:<key:\"ttl\" value:\"0\"> partition_key_columns:<type:<basic:VARCHAR> name:\"key\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p0\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p1\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p2\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p3\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p4\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p5\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p6\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p7\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p8\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p9\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p10\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p11\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p12\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p13\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p14\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p15\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p16\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p17\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p18\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p19\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p20\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p21\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p22\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p23\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p24\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p25\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p26\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p27\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p28\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p29\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p30\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p31\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p32\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p33\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p34\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p35\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p36\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p37\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p38\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p39\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p40\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p41\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p42\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p43\"> clustering_key_columns:<type:<basic:VARCHAR> name:\"p44\"> columns:<type:<basic:BOOLEAN> name:\"bool_value\"> columns:<type:<basic:DOUBLE> name:\"dbl_value\"> columns:<type:<basic:VARCHAR> name:\"leaf\"> columns:<type:<basic:VARCHAR> name:\"text_value\"> clustering_orders:<key:\"p0\" value:ASC> clustering_orders:<key:\"p1\" value:ASC> clustering_orders:<key:\"p10\" value:ASC> clustering_orders:<key:\"p11\" value:ASC> clustering_orders:<key:\"p12\" value:ASC> clustering_orders:<key:\"p13\" value:ASC> clustering_orders:<key:\"p14\" value:ASC> clustering_orders:<key:\"p15\" value:ASC> clustering_orders:<key:\"p16\" value:ASC> clustering_orders:<key:\"p17\" value:ASC> clustering_orders:<key:\"p18\" value:ASC> clustering_orders:<key:\"p19\" value:ASC> clustering_orders:<key:\"p2\" value:ASC> clustering_orders:<key:\"p20\" value:ASC> clustering_orders:<key:\"p21\" value:ASC> clustering_orders:<key:\"p22\" value:ASC> clustering_orders:<key:\"p23\" value:ASC> clustering_orders:<key:\"p24\" value:ASC> clustering_orders:<key:\"p25\" value:ASC> clustering_orders:<key:\"p26\" value:ASC> clustering_orders:<key:\"p27\" value:ASC> clustering_orders:<key:\"p28\" value:ASC> clustering_orders:<key:\"p29\" value:ASC> clustering_orders:<key:\"p3\" value:ASC> clustering_orders:<key:\"p30\" value:ASC> clustering_orders:<key:\"p31\" value:ASC> clustering_orders:<key:\"p32\" value:ASC> clustering_orders:<key:\"p33\" value:ASC> clustering_orders:<key:\"p34\" value:ASC> clustering_orders:<key:\"p35\" value:ASC> clustering_orders:<key:\"p36\" value:ASC> clustering_orders:<key:\"p37\" value:ASC> clustering_orders:<key:\"p38\" value:ASC> clustering_orders:<key:\"p39\" value:ASC> clustering_orders:<key:\"p4\" value:ASC> clustering_orders:<key:\"p40\" value:ASC> clustering_orders:<key:\"p41\" value:ASC> clustering_orders:<key:\"p42\" value:ASC> clustering_orders:<key:\"p43\" value:ASC> clustering_orders:<key:\"p44\" value:ASC> clustering_orders:<key:\"p5\" value:ASC> clustering_orders:<key:\"p6\" value:ASC> clustering_orders:<key:\"p7\" value:ASC> clustering_orders:<key:\"p8\" value:ASC> clustering_orders:<key:\"p9\" value:ASC> indexes:<name:\"docs_collection_dbl_value_idx\" column_name:\"dbl_value\"> indexes:<name:\"docs_collection_bool_value_idx\" column_name:\"bool_value\"> indexes:<name:\"docs_collection_text_value_idx\" column_name:\"text_value\"> indexes:<name:\"docs_collection_leaf_idx\" column_name:\"leaf\">> hash:<value:2009911283 >","error":null}
```

![image](https://user-images.githubusercontent.com/10600041/180804601-cb06d2f8-5824-4bb7-a5a5-3c26fd1042aa.png)

**Comment by mpenick** [comment] 2022-07-26 20:19
I'm able to reproduce using the following:

* Run cassandra cluster (use `ccm` or whatever)
* Create CQL schema:

```cql
CREATE KEYSPACE IF NOT EXISTS ks 
WITH REPLICATION = {     'class' : 'SimpleStrategy',  'replication_factor': 1   };

CREATE TABLE IF NOT EXISTS ks.test (k text, v1 text, v2 text,  PRIMARY KEY (k, v1));
```

* Startup two coordinators

```
JAVA_OPTS="-Dcassandra.allow_unsafe_join=true" ./starctl-coordinator --cluster-name cluster --cluster-version 4.0  \
  --cluster-seed 127.0.0.11 --dc dc1 --rack r1 --listen 127.0.0.1 --bind-to-listen-address --jmx-port 7001

JAVA_OPTS="-Dcassandra.allow_unsafe_join=true" ./starctl-coordinator --cluster-name cluster --cluster-version 4.0  \
  --cluster-seed 127.0.0.11 --dc dc1 --rack r1 --listen 127.0.0.2 --bind-to-listen-address --jmx-port 7002
```

* Query each coordinator using `describeKeyspace`. Each coordinator returns a different hash :scream:.

```
127.0.0.1:

hash {
  value: 1723496260
}

127.0.0.2:

hash {
  value: -714434296
}
```

**Comment by mpenick** [comment] 2022-07-26 20:30
Only thing different is the hash:

![image](https://user-images.githubusercontent.com/3710715/181106199-44632080-4759-40b7-8612-cb495e396ae6.png)

**Comment by mpenick** [comment] 2022-07-26 21:47
After a bunch of debugging it looks like relying on `.hashCode()` for the value is a bad idea. Different executions of the JVM can return different values for different executions. One example I can see is that:

```
  @Test
  public void conversionTest() {
    ColumnType type = Conversion.getTypeFromInternal(UTF8Type.instance);
    System.out.println(type.hashCode());
  }
```

Some type `ColumnType` can have different values when construction `Column` values for tables.

**Comment by ivansenic** [comment] 2022-07-28 10:33
Imo we have 2 options:

1. As @mpenick suggested, create a way to calculate keyspace hash by using the schema ID calculation code.. But after checking that, I am not sure if this is easy.. Anyway would require the impl in all the persistence modules.. I guess this is by far best solution..
2. Another way would be to connect to the schema UUID and use that.. Sure, this means that all keyspaces are invalidated on a single change, but is easy to implement and by far better than current situation. Optionally, we could enable mechnism of checking which keyspaces where changed in schema change events and update IDs only for those..

I know @tatu-at-datastax was mentioning another hashing option, but I am not sure what that was..

**Comment by mpenick** [comment] 2022-07-28 12:59
One idea is to use an alternate chain of hash calculations functions called `schemaHashCode()` where every component object implements that method using a stable hashcode calculation i.e. using `.ordinal()` for enums, etc.

**Comment by tatu-at-datastax** [comment] 2022-08-08 18:35
I think my earlier comment was wrt use of MurMur hash for content (String or `byte[]`) of Schema itself.
But if and when the issue is simple `Enum`, I agree that just using `.ordinal()` makes sense (there are alternatives like `.name.hashCode()` but I don't think there's much benefit).

**Comment by tatu-at-datastax** [comment] 2022-09-28 22:01
I think this was fixed by @mpenick 's PR, closing.

**Closed by tatu-at-datastax** 2022-09-28 22:01 UTC
Labels: bug, stargate-v2
