### ISSUE TITLE
CQL module needs to be upgraded

### ISSUE THREAD

**Issue by tjake** [stargate/stargate#2015] opened 2022-08-03 18:04 UTC
It looks like the cql module has not been upgraded to include the official V5 protocol version

https://github.com/stargate/stargate/blob/master/persistence-api/src/main/java/org/apache/cassandra/stargate/transport/ProtocolVersion.java#L41

This module needs to be upgraded to support V5 as it's the current prod version.

**Comment by mpenick** [comment] 2022-08-03 18:36
This is a duplicate of https://github.com/stargate/stargate/issues/770

**Closed** 2022-08-03 18:37 UTC
Labels: cql
