### ISSUE TITLE
Batch write endpoint for the documents API

### ISSUE THREAD

**Issue by EricBorczuk** [stargate/stargate#655] opened 2021-02-09 19:13 UTC
Upon supplying many documents to a special endpoint, we should be able to bulk-write to Cassandra

Currently, one can only hit a "single write" endpoint and that makes things inexcusably slow for 100's of thousands of documents.

**Comment by edwardoliveira** [comment] 2021-02-17 19:41
Hi @EricBorczuk and @dougwettlaufer,

Isn't this issue a duplicate of https://github.com/stargate/stargate/issues/586 ?

**Comment by eribeiro** [comment] 2021-02-18 21:35
Hi @EricBorczuk and @dougwettlaufer,

Isn't this issue a duplicate of #586 ?

**Comment by dougwettlaufer** [comment] 2021-02-18 21:39
Closing as duplicate

**Closed by dougwettlaufer** 2021-02-18 21:39 UTC
Labels: documents API
