### ISSUE TITLE
Keyspace Creation with DC information KO in V2

### ISSUE THREAD

**Issue by clun** [stargate/stargate#2231] opened 2022-11-13 17:57 UTC
The following request is not passing anymore.

Docker image
```
stargateio/restapi:v2
```

**METHOD**: `POST`
**URL**: `http://localhost:8082/v2/schemas/keyspaces/`
**BODY:**

```json
{ 
    "name":"ks3",
    "datacenters":[
        {"name":"dc1","replicas":1}
    ]
}
```

Error Messages:
```json
{
    "description": "Invalid state or argument(s) for gRPC operation (Status.Code.FAILED_PRECONDITION->400): FAILED_PRECONDITION: Unrecognized strategy option {dc1} passed to NetworkTopologyStrategy for keyspace ks3",
    "code": 400,
    "grpcStatus": "FAILED_PRECONDITION",
    "internalTxId": null
}
```

CURL COMMAND (token to update)
```
curl --location --request POST 'http://localhost:8082/v2/schemas/keyspaces/' \
--header 'X-Cassandra-Token: f19d846e-2b8d-4c9f-8ac5-6491eec1234e' \
--header 'Content-Type: application/json' \
--data-raw '{ 
    "name":"ks3",
    "datacenters":[
        {"name":"dc1","replicas":1}
    ]
}'
```

* It is still what's written in the swagger (cannot use the swagger-UI with a token, i got an error not sure why)

<img width="1442" alt="Screenshot 2022-11-13 at 6 57 52 PM" src="https://user-images.githubusercontent.com/726536/201536914-55ca3df9-93a7-4e15-9a55-b3d7115fadb1.png">

----

* Not related but `grpcStatus` and `internalTxId` should probably not be part of the public output . The exception coming from the bridge should be swallowed and converted to explicit error message*

**Comment by ivansenic** [comment] 2022-11-21 13:24
@jeffreyscarpenter @tatu-at-datastax your thinking on the proposal to hide `internalTxId` and `grpcStatus`? I think grpc status has some helpful insights.

**Comment by tatu-at-datastax** [comment] 2022-11-21 21:20
@ivansenic  I would keep `grpcStatus` available for sure. If we had internal id to expose (and one that is logged and available through logs and/or Splunk), I would want to expose that too for troubleshooting.

So I guess I do not agree in hiding these things as they can be helpful for our support people and maintainers. If anything we could consider if exposing additional aspects would be helpful.
The main benefit of error information to me is to help figure out what went wrong: some of this is useful for developers making calls, some to people maintaining and developing service.

**Comment by tatu-at-datastax** [comment] 2022-11-21 21:42
Weird thing is, we actually have test for this case too, and it is passing with shown JSON structure.
Failure message probably comes from Cassandra itself, at least I don't see anything similar in Stargate.

@clun which backend is this with?

**Comment by ivansenic** [comment] 2022-11-22 10:49
Wait how can the failure come from Cassandra, when the response JSON is from Stargate? What's the test testing it? @tatu-at-datastax You don't need the logs, just debug it..

**Comment by tatu-at-datastax** [comment] 2022-11-22 18:38
Ok so, turns out the easiest way to get log output on IDE is to avoid building Service as Docker container -- if so, it's run in JVM and output is visible as expected.

And this leads to something odd: it looks as if the test that should pass similar structure as what @clun sends instead somehow sends "simple" definition, like:

```
{"name": "ks_ks_keyspacecreatewithexplicitdc_1669142040702", "replicas": 1}
```

which is very weird... I'll need to see why this is. That would explain why test does not hit the same problem; it is not sending same data. But... why.

**Comment by tatu-at-datastax** [comment] 2022-11-22 19:02
Ok, I can reproduce the problem with specific `curl` command. So it's not the case of using an older Stargate version.

**Comment by tatu-at-datastax** [comment] 2022-11-22 19:10
Ok, I may have figure out the problem.

First of all, problem description is sort of misleading/confusing, but if I:

* Use a bogus datacenter id instead of `dc1` I get similar failure message
* Use what seems to be the default datacenter for our setup -- `datacenter1` -- call succeeds.

So I think the root cause is really use of wrong datacenter id. It is unfortunate but different backends (Cassandra docker images) appear to use different default datacenter ids. I now remember struggling with this for Integration Tests. As far as I can see we have:

* DSE-6.8: `dc1`
* Cassandra 3.11: `datacenter1`
* Cassandra 4.0: `datacenter1`
* CNDB: ???

A big follow-up question is, I think, if we could improve error messaging here.

**Comment by tatu-at-datastax** [comment] 2022-12-08 21:02
Update: I will try to handle failure better, translate into more useful failure.

**Comment by tatu-at-datastax** [comment] 2022-12-08 23:34
@clun Quick question: is this with Cassandra-4.0? I am seeing difference in behavior; it's as if C-3.11 did not actually even validate DC passed.

**Comment by tlasica** [comment] 2022-12-10 11:24
> Suppressed: org.apache.cassandra.exceptions.ConfigurationException: Unrecognized strategy option {dc1} passed to NetworkTopologyStrategy for keyspace ks3

IMO this suggests that dc name is not wrapped with single quotes.
DSE provides very precise error statement, at least int the `python driver`

```<Error from server: code=2300 [Query invalid because of configuration issue] message="Unknown data-center name 'XYZ' passed to NetworkTopologyStrategy for keyspace 'ks_invalid_dc991': it is either unknown to the configured snitch, or has no active member (known DCs: {Solr: 3 nodes})"```

**Comment by tatu-at-datastax** [comment] 2022-12-12 21:10
This is odd then: code used does use single quotes correctly it seems to be (QueryBuilder for general, but string concatenation for options) -- generated from REST API call -- and difference in working/non-working values has no difference wrt quotable characters either (`dc1` vs `datacenter1`). So this is still a mystery.

**Comment by tatu-at-datastax** [comment] 2022-12-12 22:06
@olim7t I wonder if you might have any idea of what might be causing issues here. Looks like DSE handles request to create keyspace for non-existing DC fine, reports as such. But Stargate only receives a strange error message. As far as I can see, single-quote escaping of the name is fine. It almost sounds like something in Stargate persistence implementation mapped things incorrectly or something, for DSE. No issue with Cassandra 4.0 backend.

**Comment by tatu-at-datastax** [comment] 2023-01-03 23:30
So:

1. There does NOT seem to be issue with creation of keyspace but rather use of non-existing data center. But there is sub-optimal failure message
2. PR #2302 tries to improve error reporting, with mixed success. There is a follow-up ticket for one of backends, resolution (if any) of which could lead to further improvements to error reporting

I will close this issue as resolved.

**Closed by tatu-at-datastax** 2023-01-03 23:30 UTC
Labels: bug, REST, stargate-v2
